pipeline:
    flake:
        image: python:3.5
        commands:
            - pip install flake8
            - pip install -r requirements.txt
            - flake8
        when:
            event: [push, pull_request, deployment]
    build:
        image: python:3.5
        commands:
            - pip install flake8 pyinstaller
            - pip install -r requirements.txt
            - flake8
            - pyinstaller -F -n subnetter-${DRONE_TAG}-linux-x64 subnetter.py
        when:
            event: tag
    github_release:
        image: plugins/github-release
        files: dist/*
        when:
            event: tag
