pipeline:
    build:
        image: python:3.5.3
        commands:
            - pip install tox flake8 pyinstaller
            - pip install -r requirements.txt
            - flake8
            - tox
            - pyinstaller -F -n subnetter-linux-x64 subnetter.py
    github_release:
        image: plugins/github-release
        files: dist/subnetter-linux-x64
        when:
            event: tag
